# Generated by Django 4.2 on 2023-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessopeningtrainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='eco',
            field=models.CharField(default='', max_length=255),
        ),
    ]
